pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        gradlePluginPortal()
        mavenLocal()
    }
}

rootProject.name = 'aotake-sweep'

includeBuild('../BaniraCodex') {
    dependencySubstitution {
        substitute(module('xin.vanilla.banira:banira_codex')).using(project(':'))
    }
}
